name: Readability

on: pull_request

jobs:
  scoreText:
    name: Get text to score
    runs-on: ubuntu-latest
    steps:
      - name: Checkout into docdoctor
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: 'docdoctor'
      - name: Get file paths for files to score
        id: getPaths
        uses: tj-actions/changed-files@v23.2
        with: 
          path: 'docdoctor'
      - name: List changed file paths to variable
        id: listPaths
        run: |
          absolutePaths=""
          for filePath in ${{ steps.getPaths.outputs.all_changed_files }}; do
            absolutePaths="$absolutePaths docdoctor/$filePath"
          done
          echo '::set-output name=CHANGED_FILE_PATHS::$absolutePaths'
      - name: Get docdoctor
        uses: actions/checkout@v3
        with: 
          repository: dacharyc/docdoctor
          ref: 'readability'
          path: 'docdoctor'
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Generate text from rST
        working-directory: 'docdoctor'
        run: |
          npm i
          npm run build
          ls
          echo 'CHANGED_FILE_PATHS is ${{ steps.listPaths.outputs.CHANGED_FILE_PATHS }}'
          node . getReadabilityText ${{ steps.listPaths.outputs.CHANGED_FILE_PATHS }}
