name: Readability

on: pull_request

jobs:
  scoreText:
    name: Parse text, score text, and report scores on PR.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo.
        uses: actions/checkout@v3
      - name: Get changed files.
        id: changed-files
        uses: tj-actions/changed-files@v23.2
      - name: List changed files (debugging log statement).
        run: |
          echo ${{ steps.changed-files.outputs.all_changed_files }}
      - name: Checkout docdoctor repo.
        uses: actions/checkout@v3
        with: 
          repository: dacharyc/docdoctor
          ref: 'readability'
          path: 'docdoctor'
      - name: Install Node.js.
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Parse text from rST.
        run: |
          npm install $GITHUB_WORKSPACE/docdoctor
          npm run build
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            node $GITHUB_WORKSPACE/docdoctor getReadabilityText $GITHUB_WORKSPACE/$file
          done
