name: Readability

on: pull_request

jobs:
  scoreText:
    name: Get text to score
    runs-on: ubuntu-latest
    steps:
      - name: Get file paths for files to score
        id: getPaths
        uses: jitterbit/get-changed-files@v1
        run: |
          echo '::set-output name=CHANGED_FILE_PATHS::${{ steps.files.outputs.all }}'
      - name: Get docdoctor
        uses: actions/checkout@v3
        with: 
          repository: dacharyc/docdoctor
          ref: 'readability'
          path: 'docdoctor'
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Generate text from rST
        working-directory: docdoctor
        run: |
          npm i
          npm run build
          node . getReadabilityText ${{ steps.getPaths.outputs.CHANGED_FILE_PATHS }}
